version: '3'
services:
  backoffice:
    container_name: eco-frontoffice
    build:
      context: .
      dockerfile: ./Dockerfile
    image: eco-frontoffice:latest
    ports:
      - "80:8080"
    command: [ "http-server", "dist" ]

