version: '3'
services:
  backoffice:
    container_name: eco-frontoffice
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./certificate.pem:/app/certificate.pem
      - ./key.pem:/app/key.pem
    image: eco-frontoffice:latest
    ports:
      - "8080:8080"
    command: [ "http-server", "dist", "--ssl", "--cert", "certificate.pem", "--key", "key.pem"]
